export const blogsData = [
    {
        id: 1,
        title : 'Almost half of SoftBanks India portfolio cos are close to or above breakeven: BofA',
        shortDesc: 'The report highlighted that the cost-cutting measures resulted in reduced growth rates of 15-30 percent for startups, compared to their previous growth rate of 60-80 percent.',
        desc: 'Nearly half of SoftBanks Indian portfolio companies are close to or above breakeven, according to a report by investment bank Bank of America (BofA). The report said that these companies did a good job in cutting costs materially in the last 6-9 months, as startups grappled with a funding winter amid a deteriorating macroeconomic environment. The report highlighted that the cost-cutting measures resulted in reduced growth rates of 15-30 percent for startups, compared to their previous growth rate of 60-80 percent. However, the report also emphasised that these initiatives extended the companies cash runways, with approximately 94% of SoftBanks investee companies having at least a 12-month cash runway by the end of March 2023. Earlier this month, Moneycontrol reported that SoftBanks investee companies in India had cut costs between 50 and 75 percent over the last 12-15 months by implementing various cost-cutting initiatives. The Japanese investment conglomerates portfolio companies in India have laid off more than 7,500 employees since the start of 2022. SoftBank has been a prolific investor in Indian startups over the last decade, investing close to $15 billion. Most of these investments have happened in the recent past. But the investment conglomerate has changed its investing approach, particularly since 2019, when it established an on-ground team in India, its third-largest market after the US and China. The BofA report also argued the same.',
        author: 'Anuj Singh',
        image: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80'
    },
    {
        id: 2,
        title : 'Fintech soonicorn Kinara Capital looks to raise $150-$200 million',
        shortDesc: 'Launched in 2011, the firm led by Founder & CEO Hardika Shah has raised over $500 million in capital (equity and debt), from India-based and global investors till date',
        desc: 'Bengaluru-headquartered fintech soonicorn Kinara Capital, which focuses on financial inclusion of small business entrepreneurs, is on the prowl for funds again and is looking to mop up around $150 million to $200 million, multiple industry sources in the know told Moneycontrol. "Yes, Kinara is back in fund raise mode. They are in discussions with investment bank Edelweiss Financial Services as advisors. Edelweiss had helped the firm in its last round as well," said one of the persons above. Two other persons confirmed the proposed transaction, and one of them added that Kinara Capital needed fresh growth capital.In response to an email query from Moneycontrol, Hardika Shah, Founder and CEO, Kinara Capital said, "For over a decade, Kinara Capital has demonstrated scale and profitability as a leading MSME lender, especially by providing access to collateral-free credit. As we continue to grow, we will diversify our product offerings to meet the vast credit demand in the MSME sector. For this, we are looking for growth capital to expand financial inclusion to the much deserving, but the much underserved, MSME sector of India.” Moneycontrol has sent an email query but could not elicit an immediate response from Edelweiss Financial Services. This article will be updated once we hear from the firm.',
        author: 'Anuj Singh',
        image: 'https://images.unsplash.com/photo-1584134239909-eb4800257d6a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80'
    },
    {
        id: 3,
        title : 'BlackRock cuts Byjus fair value by 62% for the second time since October 2022',
        shortDesc: 'BlackRock, which holds less than 1 percent, has pegged the value of its 2,279 shares in the company at $4,043,471, effectively estimating Byjus fair value at $8.4 billion as of March 31, 2023.',
        desc: 'BlackRock, the worlds largest asset management company (AMC), has reduced the fair value of Byjus, the worlds most-valued edtech startup, by 62 percent. This is the second time BlackRock has reduced the fair value of Byjus since October 2022. BlackRock, which holds less than 1 percent, has pegged the value of its 2,279 shares in the company at $4,043,471, effectively estimating Byjus fair value at $8.4 billion as of March 31, 2023. As of April last year, the company estimated Byjus valuation to be north of $22 billion, according to the AMCs filings with the Securities and Exchange Commission (SEC). According to the filings, BlackRock also sold shares in Byjs during the period. Byjus declined to comment. Inc42 first reported about the development. To be sure, these adjustments to fair values are typically based on AMCs internal assessment of the macro and microenvironment. They do not necessarily indicate a permanent markdown in the startups overall valuation. Blackrock also holds only a minority stake in the company and thus has access to limited information about the companys operations. The markdown, however, comes at a time when Byjus is gearing up for a massive fundraise worth almost a billion dollars, its second flat funding round, from a clutch of investors in the Middle East and the US. The company has already raised $250 million through structured instruments and is finalising another $700 million in equity.',
        author: 'Anuj Singh',
        image: 'https://plus.unsplash.com/premium_photo-1682787495017-a8f4c7584868?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80'
    }
]